file(READ "${CMAKE_SOURCE_DIR}/eng/architecture.json" NENE_ARCHITECTURE)

function(neneloupe_target target module kind)
    string(JSON module_path ERROR_VARIABLE module_error GET "${NENE_ARCHITECTURE}" modules "${module}" path)
    if(module_error)
        message(FATAL_ERROR "ARC-002: unapproved module ${module}")
    endif()
    if(NOT ARGN)
        message(FATAL_ERROR "ARC-002: empty future modules are forbidden")
    endif()
    foreach(source IN LISTS ARGN)
        cmake_path(ABSOLUTE_PATH source BASE_DIRECTORY "${CMAKE_SOURCE_DIR}" NORMALIZE OUTPUT_VARIABLE absolute_source)
        set(module_root "${CMAKE_SOURCE_DIR}/${module_path}")
        cmake_path(IS_PREFIX module_root "${absolute_source}" NORMALIZE inside)
        if(NOT inside)
            message(FATAL_ERROR "ARC-002: ${source} does not belong to ${module}")
        endif()
    endforeach()
    if(kind STREQUAL "EXECUTABLE")
        add_executable(${target} ${ARGN})
    elseif(kind STREQUAL "STATIC")
        add_library(${target} STATIC ${ARGN})
    else()
        message(FATAL_ERROR "ARC-002: unsupported target kind ${kind}")
    endif()
    set_property(TARGET ${target} PROPERTY NENE_MODULE "${module}")
    target_compile_options(${target} PRIVATE /W4 /WX /permissive- /we4061 /we4062 /utf-8)
    target_include_directories(${target} PUBLIC "${CMAKE_SOURCE_DIR}/${module_path}")
    if(module MATCHES "^(adapters_win32|ui_win32|app)$")
        target_compile_definitions(${target} PRIVATE UNICODE _UNICODE WIN32_LEAN_AND_MEAN NOMINMAX)
    endif()
endfunction()

function(neneloupe_system_link target library)
    get_target_property(module ${target} NENE_MODULE)
    string(JSON allowed ERROR_VARIABLE error GET "${NENE_ARCHITECTURE}" platformLibraries "${module}")
    if(error)
        message(FATAL_ERROR "ARC-002: no platform libraries for ${module}")
    endif()
    string(JSON count LENGTH "${allowed}")
    math(EXPR last "${count} - 1")
    foreach(index RANGE 0 ${last})
        string(JSON candidate GET "${allowed}" ${index})
        if(candidate STREQUAL library)
            target_link_libraries(${target} PRIVATE ${library})
            return()
        endif()
    endforeach()
    message(FATAL_ERROR "ARC-002: forbidden platform library ${module} -> ${library}")
endfunction()

function(neneloupe_link target dependency)
    get_target_property(module ${target} NENE_MODULE)
    get_target_property(destination ${dependency} NENE_MODULE)
    string(JSON allowed GET "${NENE_ARCHITECTURE}" modules "${module}" dependencies)
    string(JSON count LENGTH "${allowed}")
    set(found FALSE)
    if(count GREATER 0)
        math(EXPR last "${count} - 1")
        foreach(index RANGE 0 ${last})
            string(JSON candidate GET "${allowed}" ${index})
            if(candidate STREQUAL destination)
                set(found TRUE)
            endif()
        endforeach()
    endif()
    if(NOT found)
        message(FATAL_ERROR "ARC-002: forbidden dependency ${module} -> ${destination}")
    endif()
    target_link_libraries(${target} PRIVATE ${dependency})
endfunction()
